sonar.projectName=UsahainAja Frontend
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx
sonar.exclusions=node_modules/**,dist/**,coverage/**,src/vite-env.d.ts
sonar.coverage.exclusions=src/main.tsx,src/vite-env.d.ts
